    export const Industries = [
    "Industries",
    "Accountants",
    "Advertising/Public Relations",
    "Administration and Finance",
    "Agribusiness",
    "Agricultural Services & Products",
    "Agriculture",
    "Airlines",
    "Alcoholic Beverages",
    "Alternative Energy Production & Services",
    "Architectural Services",
    "Attorneys/Law Firms",
    "Auto Dealers",
    "Auto Manufacturers",
    "Automotive",
    "Banking, Mortgage",
    "Banks, Commercial",
    "Bars & Restaurants",
    "Books, Magazines & Newspapers",
    "Broadcasters, Radio/TV",
    "Builders/General Contractors",
    "Building Materials & Equipment",
    "Business Associations",
    "Business Services",
    "Cable & Satellite TV Production & Distribution",
    "Car Dealers, Imports",
    "Casinos / Gambling",
    "Cattle Ranchers/Livestock",
    "Chemical & Related Manufacturing",
    "Civil Servants/Public Officials",
    "Clergy & Religious Organizations",
    "Clothing Manufacturing",
    "Coal Mining",
    "Colleges, Un'iversities & Schools",
    "Commercial Banks",
    "Commercial TV & R'adio Stations",
    "Communications/Electronics",
    "Computer Software",
    "Construction",
    "Construction Services",
    "Crop Production & Basi'c Processing",
    "Cruise Ships & Lines",
    "Dentists",
    "Doctors & Other Health Professionals",
    "Drug Manufacturers",
    "Education",
    "Electric Utilities",
    "Electronics Manufacturing & Equipment",
    "Energy & Natural Resources",
    "Engineering",
    "Engineering/Electrical and Electronics",
    "Engineering/Civil",
    "Engineering/Mechanical",
    "Entertainment Industry",
    "Environment",
    "Farming",
    "Finance / Credit Companies",
    "Finance, Insurance & Real Estate",
    "Food & Beverage",
    "Food Products Manufacturing",
    "For-profit Education",
    "Forestry & Forest Products",
    "Foundations, Philanthropists & Non-Profits",
    "Funeral Services",
    "Gambling & Casinos",
    "Garbage Collection/Waste Management",
    "Gas & Oil",
    "General Contractors",
    "Government Employee Unions",
    "Health Professionals",
    "Health Services",
    "Hospitals & Nursing Homes",
    "Hotels, Motels & Tourism",
    "Human Rights",
    "Industrial Unions",
    "INGO",
    "Insurance",
    "Internet",
    "Labor",
    "Lawyers / Law Firm",
    "Livestock",
    "Lodging / Tourism",
    "Marine Transport",
    "Meat processing & products",
    "Medical Supplies",
    "Mining",
    "Mortgage Bankers & Brokers",
    "Motion Picture Production & Distribution",
    "Music Production",
    "Newspaper, Magazine & Book Publishing",
    "NGO",
    "Non-profits, Foundations & Philanthropists",
    "Nursing Homes/Hospitals",
    "Nutritional & Dietary Supplements",
    "Oil & Gas",
    "Pharmaceuticals / Health Products",
    "Phone Companies",
    "Physicians & Other Health Professionals",
    "Poultry & Eggs",
    "Power Utilities",
    "Printing & Publishing",
    "Private Equity & Investment Firms",
    "Professional Sports, Sports Arenas & Related Equipment & Services",
    "Public Sector Unions",
    "Record Companies/Singers",
    "Recreation / Live Entertainment",
    "Religious Organizations/Clergy",
    "Restaurants & Drinking Establishments",
    "Securities & Investment",
    "Sports, Professional",
    "Sugar Cane & Sugar Beets",
    "Teachers Unions",
    "Textiles",
    "Tobacco",
    "Transportation",
    "Transportation Unions",
    "Trash Collection/Waste Management",
    "Trucking",
    "TV / Movies / Music",
    "TV Production",
    "Unions",
    "Vegetables & Fruits",
    "Venture Capital",
    "Waste Management",
    "Wine, Beer & Liquor",
    "Women's Issues",
    ];

export const Districts = [
        "District",
        "Bo",
        "Bombali",
        "Bonthe",
        "Falaba",
        "Freetown",
        "Kailahun",
        "Kambia",
        "Karene",
        "Kenema",
        "Koinadugu",
        "Kono",
        "Moyamba",
        "Port-Loko",
        "Pujehun",
        "Tonkolili"
    
];

export const Months = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]

export const Days = [
    1,2,3,4,5,
    6,7,8,9,10,
    11,12,13,14,
    15,16,17,18,19,
    20,21,22,23,24,25,26,
    27,28,29,30,31
]

let years = []
for (let i=1000; i<new Date().getFullYear(); i++) {
    years.push(i)
}

export const Years = years;